Repository BritishGeologicalSurvey/etlhelper, pull requests merged in 2019-11, with the labels that each got.

#15 fix broken pypi link
  README.md
Labels: documentation

#19 Change instances of sql_server to mssql for consistency
  README.md
  etlhelper/db_helper_factory.py
  etlhelper/db_helpers/__init__.py
  etlhelper/db_helpers/mssql.py
  etlhelper/setup_mssql_server_driver.py
  test/unit/test_helper_factory.py
Labels: enhancement

#20 Add Python 3.8 to Travis CI
  .travis.yml
Labels: continuous-integration
